import json
import re
import urllib.request
from pathlib import Path
from datetime import datetime

ORCID = "0000-0003-3599-3404"
API_URL = f"https://pub.orcid.org/v3.0/{ORCID}/works"

PUBLICATIONS_DIR = Path("_publications")
PUBLICATIONS_DIR.mkdir(exist_ok=True)


def get_json(url):
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.orcid+json",
            "User-Agent": "Evrim-Anik-Academic-Website"
        }
    )

    with urllib.request.urlopen(request) as response:
        return json.loads(response.read().decode("utf-8"))


def clean_filename(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-+", "-", text)
    return text.strip("-")[:80]


def clean_text(text):
    if not text:
        return ""
    return (
        text.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", " ")
            .replace("\r", " ")
    )


def get_year(work):
    publication_date = work.get("publication-date")

    if publication_date and publication_date.get("year"):
        return publication_date["year"].get("value")

    return "1900"


def get_title(work):
    title = work.get("title", {})
    title_data = title.get("title", {})
    return title_data.get("value", "Untitled publication")


def get_journal(work):
    journal = work.get("journal-title")

    if journal:
        return journal.get("value", "")

    return ""


def get_doi(work):
    external_ids = work.get("external-ids", {}).get("external-id", [])

    for external_id in external_ids:
        if external_id.get("external-id-type", "").lower() == "doi":
            return external_id.get("external-id-value", "")

    return ""


def get_url(work):
    doi = get_doi(work)

    if doi:
        doi = doi.replace("https://doi.org/", "").replace("http://doi.org/", "")
        return f"https://doi.org/{doi}"

    return ""


def get_category(work):
    work_type = work.get("type", "").lower()

    if "conference" in work_type:
        return "conferences"

    if work_type in ["book", "book-chapter"]:
        return "books"

    return "manuscripts"


def make_publication_file(work, put_code):
    title = get_title(work)
    year = get_year(work)
    journal = get_journal(work)
    doi_url = get_url(work)
    category = get_category(work)

    filename_title = clean_filename(title)

    filename = (
        f"{year}-01-01-{filename_title}-{put_code}.md"
    )

    filepath = PUBLICATIONS_DIR / filename

    citation = title

    if journal:
        citation += f". {journal}."

    if doi_url:
        citation += f" {doi_url}"

    content = f"""---
title: "{clean_text(title)}"
collection: publications
category: "{category}"
date: {year}-01-01
venue: "{clean_text(journal)}"
paperurl: "{doi_url}"
citation: "{clean_text(citation)}"
excerpt: "Publication imported automatically from ORCID."
---

<!-- ORCID_PUT_CODE: {put_code} -->
"""

    filepath.write_text(content, encoding="utf-8")

    print(f"Created/updated: {filepath}")


def main():

    print("Retrieving publications from ORCID...")
    data = get_json(API_URL)

    groups = data.get("group", [])

    print(f"Found {len(groups)} ORCID work groups.")

    current_put_codes = set()

    for group in groups:

        summaries = group.get("work-summary", [])

        if not summaries:
            continue

        work = summaries[0]

        put_code = str(work.get("put-code"))

        if not put_code:
            continue

        current_put_codes.add(put_code)

        # Retrieve full work record
        full_url = f"{API_URL}/{put_code}"
        full_work = get_json(full_url)

        make_publication_file(full_work, put_code)

    # Remove files previously generated by this script
    # if their ORCID record no longer exists.
    for filepath in PUBLICATIONS_DIR.glob("*.md"):

        text = filepath.read_text(encoding="utf-8")

        match = re.search(
            r"ORCID_PUT_CODE:\s*(\d+)",
            text
        )

        if match:

            put_code = match.group(1)

            if put_code not in current_put_codes:

                print(f"Removing deleted ORCID publication: {filepath}")
                filepath.unlink()

    print("ORCID publication update complete.")


if __name__ == "__main__":
    main()
